### ISSUE TITLE
undefined method `liquid_methods' for class `Object'

### ISSUE THREAD

**Issue by jc00ke** [awesome-print/awesome_print#16]
Hasn't worked with Rails 3.0.1 or 3.0.3

```
$> ./script/rails server -u
/opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap/core_ext/object.rb:10: undefined method `liquid_methods' for class `Object' (NameError)
    from /opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap/core_ext/array.rb:59:in `grep'
    from /opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap/core_ext/object.rb:17:in `original_grep'
    from /opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap/core_ext/array.rb:59:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap/core_ext/array.rb:59:in `original_grep'
    from /opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap/core_ext/array.rb:59:in `grep'
    from /opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap/core_ext/object.rb:7
    from /opt/local/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/local/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/local/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/local/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /opt/local/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /opt/local/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap.rb:7
    from /opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap.rb:6:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/awesome_print-0.3.1/lib/ap.rb:6
    from /opt/local/lib/ruby/gems/1.8/gems/bundler-1.0.3/lib/bundler/runtime.rb:64:in `require'
    from /opt/local/lib/ruby/gems/1.8/gems/bundler-1.0.3/lib/bundler/runtime.rb:64:in `require'
    from /opt/local/lib/ruby/gems/1.8/gems/bundler-1.0.3/lib/bundler/runtime.rb:62:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/bundler-1.0.3/lib/bundler/runtime.rb:62:in `require'
    from /opt/local/lib/ruby/gems/1.8/gems/bundler-1.0.3/lib/bundler/runtime.rb:51:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/bundler-1.0.3/lib/bundler/runtime.rb:51:in `require'
    from /opt/local/lib/ruby/gems/1.8/gems/bundler-1.0.3/lib/bundler.rb:112:in `require'
    from /Users/jesse/projects/projectdx-pdxrails/config/application.rb:7
    from /opt/local/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:28:in `require'
    from /opt/local/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:28
    from /opt/local/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:27:in `tap'
    from /opt/local/lib/ruby/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:27
    from ./script/rails:6:in `require'
    from ./script/rails:6
```
